#include <vidf/pch.h>
#include <vidf/common/bitfield.h>
#include <vidf/common/box.h>
#include <vidf/proto/protogl.h>
#include <vidf/proto/camera.h>
#include <vidf/proto/protoglpragma.h>
#include <vidf/platform/time.h>
#include <vidf/platform/taskmanager.h>
#include <vidf/platform/filechangenotification.h>
#include <vidf/platform/system.h>

#include <QApplication>
#include <QTextEdit>
#include <QMainWindow>
#include <QAction>
#include <QMenuBar>
#include <QFileDialog>
#include <QMessageBox>
#include <QTextStream>
#include <QBoxLayout>
#include <QPushButton>