#define YY_CHAR char
#line 1 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"
/* A lexical scanner generated by flex */
/* scanner skeleton version:
 * $Header: c:\\Program\040Files\\Development\\CVS\040Repository/flex++/flexskel.cc,v 1.1.1.1 2002/04/13 06:01:32 Bear Exp $
 */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */
/* institutional financial group  */

/* theses symbols are added before this file */
/* #define YY_CHAR 'unsigned char' if 8bit or 'char' if 7bit */
/* #define FLEX_DEBUG if debug mode */
#define FLEX_SCANNER
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
/* Old MSC, before c7 */
#ifdef MSDOS
#ifndef _MSDOS
#define _MSDOS
#endif
#endif
/* turboc */
#ifdef __MSDOS__
#ifndef _MSDOS
#define _MSDOS
#endif
#endif

#ifdef __cplusplus
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
// #ifndef _MSDOS
// #include <osfcn.h>
// #endif
#else   /* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#include <stddef.h>
void *malloc( size_t );
void free( void* );
int read();
#else
#include <stdlib.h>
#endif  /* __GNUC__ */
#define YY_USE_PROTOS
#define YY_USE_CONST
#endif  /* __STDC__ */
#endif  /* ! __cplusplus */
#ifdef __TURBOC__
#define YY_USE_CONST
#endif
#include <stdio.h>


/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
/* the "const" storage-class-modifier is valid */
#ifndef YY_USE_CONST
#define const
#endif
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif


/*********************/
/* parameters        */

/* amount of stuff to slurp up with each read */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif
/* size of default input buffer */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE (YY_READ_BUF_SIZE * 2) 
#endif

/***********************************/
/* to be redefined for application */

/* returned upon end-of-file */
#define YY_END_TOK 0
/* no semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#define yyterminate() return ( YY_NULL )

/* code executed at the end of each rule */
#define YY_BREAK break;

/* #define YY_USER_ACTION */
/* #define YY_USER_INIT */


#ifndef YY_USE_CLASS
/* copy whatever the last rule matched to the standard output */
/* cast to (char *) is because for 8-bit chars, yy___text is (unsigned char *) */
/* this used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite()
 */
#define ECHO (void) fwrite( (char *) yy___text, yy___leng, 1, yy___out )

/* gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifdef _MSDOS
#define YY_INPUT(buf,result,max_size) \
	if ( (result = fread(buf,1,max_size,yy___in)) < 0 ) \
	    YY_FATAL_ERROR( "fread() in flex scanner failed" );
#else
#define YY_INPUT(buf,result,max_size) \
	if ( (result = read( fileno(yy___in), (char *) buf, max_size )) < 0 ) \
	    YY_FATAL_ERROR( "read() in flex scanner failed" );

#endif
/* report a fatal error */

/* The funky do-while is used to turn this macro definition into
 * a single C statement (which needs a semi-colon terminator).
 * This avoids problems with code like:
 *
 *      if ( something_happens )
 *              YY_FATAL_ERROR( "oops, the something happened" );
 *      else
 *              everything_okay();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the YY_FATAL_ERROR() call.
 */

#define YY_FATAL_ERROR(msg) \
	do \
		{ \
		(void) fputs( msg, yy___stderr  ); \
		(void) putc( '\n', yy___stderr  ); \
		exit( 1 ); \
		} \
	while ( 0 )

/* default yywrap function - always treat EOF as an EOF */
#define yywrap() 1


/* default declaration of generated scanner - a define so the user can
 * easily add parameters
 */
#define YY_DECL int yylex YY_PROTO(( void )) 
#else 
/* c++ */
#define ECHO yy___echo()
#define YY_INPUT(buf,result,max_size) \
	if ( yy___input((char *)buf, result,max_size) < 0 ) \
	    YY_FATAL_ERROR( "YY_INPUT() in flex scanner failed" );

#define YY_FATAL_ERROR(msg) yy___fatal_error(msg)
#define yywrap() yy___wrap()

#endif
/***********************************/
/* not to be changed */
#define YY_NULL 0
#define YY_END_OF_BUFFER_CHAR 0
/* special action meaning "start processing a new file" */
#define YY_NEW_FILE yy___newfile 
/* enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN
 */
#define BEGIN yy_start = 1 + 2 *

/* action number for EOF rule of a given start state */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)



/* % section 1 definitions go here */ 
#line 1 "kcscanner.l"
#define INITIAL 0
#line 3 "kcscanner.l"
#include <stdio.h>
#include "kcparser.h"

void count(const char* yytext);
void comment();
int check_type();

#define YY_lex_FLEX_SCANNER
#include "kcscanner.h"
#line 28 "kcscanner.l"
#line 196 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"

#define yy___stderr YY_lex_ERRFILE
#define yy___text YY_lex_TEXT
#define yy___leng YY_lex_LENG
#define yy___in YY_lex_IN
#define yy___out YY_lex_OUT
#define yy___newfile \
	do \
		{ \
		YY_lex_INIT_BUFFER( YY_lex_CURRENT_BUFFER, yy___in ); \
		YY_lex_LOAD_BUFFER_STATE(); \
		} \
	while ( 0 )
#if YY_lex_DEBUG != 0
#define yy___flex_debug YY_lex_DEBUG_FLAG
#endif


#ifdef YY_USE_CLASS

#define yy___echo YY_lex_ECHO
#define yy___input YY_lex_INPUT
#define yy___fatal_error YY_lex_FATAL_ERROR
#define yy___wrap YY_lex_WRAP

#endif

/* done after the current pattern has been matched and before the
 * corresponding action - sets up yy___text
 */
#define YY_DO_BEFORE_ACTION \
	yy___text = yy_bp; \
/* % code to fiddle yy___text and yy___leng for yymore() goes here */ \
	yy___leng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* return all but the first 'n' matched characters back to the input stream */
#define yyless(n) \
	do \
		{ \
		/* undo effects of setting up yy___text */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n; \
		YY_DO_BEFORE_ACTION; /* set up yy___text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yy___text )



struct yy_buffer_state
    {
    YY_lex_IFILE  *yy_input_file;

    YY_lex_CHAR *yy_ch_buf;               /* input buffer */
    YY_lex_CHAR *yy_buf_pos;      /* current position in input buffer */

    /* size of input buffer in bytes, not including room for EOB characters */
    int yy_buf_size;    

    /* number of characters read into yy_ch_buf, not including EOB characters */
    int yy_n_chars;

    int yy_eof_status;          /* whether we've seen an EOF on this buffer */
#define EOF_NOT_SEEN 0
    /* "pending" happens when the EOF has been seen but there's still
     * some text process
     */
#define EOF_PENDING 1
#define EOF_DONE 2
    };

/* we provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state"
 */

#ifndef YY_USE_CLASS

#if YY_lex_DEBUG != 0
int YY_lex_DEBUG_FLAG=YY_lex_DEBUG_INIT;
#endif
#define YY_CURRENT_BUFFER YY_lex_CURRENT_BUFFER
static YY_BUFFER_STATE YY_lex_CURRENT_BUFFER;
/* yy_hold_char holds the character lost when yy___text is formed */
static YY_lex_CHAR yy_hold_char;

static int yy_n_chars;          /* number of characters read into yy_ch_buf */

/* GLOBAL */
YY_lex_CHAR *yy___text;
int yy___leng;

YY_lex_IFILE  *yy___in = (YY_lex_IFILE  *) 0;
YY_lex_OFILE *yy___out = (YY_lex_OFILE  *) 0;

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
/* these variables are all declared out here so that section 3 code can
 * manipulate them
 */
/* points to current character in buffer */
static YY_lex_CHAR *yy_c_buf_p = (YY_lex_CHAR *) 0;
static int yy_init = 1;         /* whether we need to initialize */
static int yy_start = 0;        /* start state number */

/* flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yy___in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static int yy_get_next_buffer YY_PROTO(( void ));
static void yyunput YY_PROTO(( YY_lex_CHAR c, YY_lex_CHAR *buf_ptr ));

#else
/* c++ */
#ifndef YY_lex_ECHO_NOCODE
void YY_lex_CLASS::yy___echo()
{YY_lex_ECHO_CODE
}
#endif
#ifndef YY_lex_INPUT_NOCODE
int  YY_lex_CLASS::yy___input(char * buffer,int &result,int max_size)
{YY_lex_INPUT_CODE
}
#endif
#ifndef YY_lex_FATAL_ERROR_NOCODE
void YY_lex_CLASS::yy___fatal_error(char *msg)
{YY_lex_FATAL_ERROR_CODE
}
#endif
#ifndef YY_lex_WRAP_NOCODE
int  YY_lex_CLASS::yy___wrap()
{YY_lex_WRAP_CODE
}
#endif
void YY_lex_CLASS::yy_initialize()
{
 yy___in=0;yy___out=0;yy_init = 1;
 yy_start=0;
 yy___text=0;yy___leng=0;
 YY_lex_CURRENT_BUFFER=0;
 yy_did_buffer_switch_on_eof=0;
 yy_c_buf_p=0;yy_hold_char=0;yy_n_chars=0;
#if YY_lex_DEBUG != 0
 YY_lex_DEBUG_FLAG=YY_lex_DEBUG_INIT;
#endif
}

YY_lex_CLASS::YY_lex_CLASS(YY_lex_CONSTRUCTOR_PARAM) YY_lex_CONSTRUCTOR_INIT
{yy_initialize();
 YY_lex_CONSTRUCTOR_CODE;
}
YY_lex_CLASS::~YY_lex_CLASS() 
{YY_lex_DESTRUCTOR_CODE;
 if(YY_lex_CURRENT_BUFFER)
  YY_lex_DELETE_BUFFER(YY_lex_CURRENT_BUFFER);
}

#endif


#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#ifndef YY_USER_INIT
#define YY_USER_INIT
#endif

/* % data tables for the DFA go here */ 
#define YY_END_OF_BUFFER 92
typedef int yy_state_type;
static const short int yy_accept[242] =
    {   0,
        0,    0,   92,   90,   89,   89,   77,   90,   83,   76,
       90,   71,   72,   81,   80,   68,   79,   75,   82,   37,
       37,   69,   65,   84,   70,   85,   88,   34,   34,   73,
       74,   86,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   66,   87,   67,
       78,   64,    0,   42,    0,   50,   67,   59,   51,    0,
        0,   48,   56,   46,   57,   47,   58,    0,   40,    1,
       49,   41,   36,    0,   37,    0,   37,   74,   66,   73,
       55,   61,   63,   62,   54,   34,    0,    0,   52,   34,
       34,   34,   34,   34,   34,    9,   34,   34,   34,   34,

       34,   34,   17,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   53,   60,   38,   43,    0,   40,
       40,    0,   41,   36,    0,   39,   35,   45,   44,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       15,   34,   18,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,    0,   40,
        0,   40,    0,   41,   39,   35,    2,   34,    4,    5,
       34,   34,   34,   34,   11,   12,   34,   34,   16,   19,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   31,   34,   34,    0,   40,    3,    6,   34,   34,

       34,   34,   14,   34,   34,   22,   34,   34,   34,   34,
       34,   34,   29,   34,   34,   33,   34,   34,   10,   13,
       34,   21,   23,   24,   25,   26,   27,   34,   34,   34,
       34,    8,   34,   28,   34,   34,    7,   20,   30,   32,
        0
    } ;

static const YY_CHAR yy_ec[128] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   27,
       28,   28,   28,   28,   28,   29,   28,   28,   28,   28,
       28,   28,   28,   28,   30,   28,   28,   31,   28,   28,
       32,   33,   34,   35,   28,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   28,   45,   46,   47,   48,
       49,   50,   28,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    4,    4,    4,
        4,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    1
    } ;

static const short int yy_base[246] =
    {   0,
        0,    0,  371,  372,  372,  372,  348,   59,   43,   60,
      336,  372,  372,  346,   56,  372,   57,   55,   63,   78,
       71,  344,  372,   84,  344,   53,  372,    0,   76,  372,
      372,  343,  310,  312,   77,   70,   66,   45,  313,   74,
      312,  320,   84,  301,  310,  308,  313,  372,   55,  372,
      372,  372,   97,  372,  352,  372,  372,  372,  372,  113,
      126,  372,  372,  372,  372,  372,  372,  339,  121,  372,
      372,  125,  155,  141,  134,    0,  160,  372,  372,  372,
      331,  372,  372,  372,  330,    0,  136,  318,  372,  297,
      309,  296,  311,  298,  304,  290,  291,  288,  288,  291,

      288,  285,    0,  284,  288,   45,  286,  115,  109,  290,
      283,   92,   87,  288,  372,  372,  372,  372,  179,  372,
      181,  199,  372,  174,  165,  206,  196,  372,  372,  282,
      294,  289,  277,  166,  291,  289,  285,  277,  283,  286,
        0,  272,    0,  278,  275,  264,  266,  268,  275,  261,
      259,  259,  271,  261,  265,  269,  271,  260,  212,  214,
      222,  372,  220,  227,  372,  228,    0,  260,    0,    0,
      247,  249,  238,  245,    0,    0,  239,  235,    0,    0,
      235,  235,  232,  244,  234,  237,  242,  241,  239,  228,
      230,    0,  218,  230,  231,  248,    0,    0,  221,  221,

      224,  215,    0,  209,  213,    0,  220,  212,  213,  193,
      172,  172,    0,  157,  158,    0,  140,  139,    0,    0,
      147,    0,    0,    0,    0,    0,    0,  138,  136,  122,
      116,    0,   98,    0,   60,   43,    0,    0,    0,    0,
      372,  294,  298,  300,   66
    } ;

static const short int yy_def[246] =
    {   0,
      241,    1,  241,  241,  241,  241,  241,  242,  241,  241,
      243,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  244,  244,  241,
      241,  241,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  241,  241,  241,
      241,  241,  242,  241,  242,  241,  241,  241,  241,  243,
      243,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  245,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  244,  242,  243,  241,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  245,  241,  241,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  241,  241,
      241,  241,  241,  241,  241,  241,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  241,  241,  244,  244,  244,  244,

      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
        0,  241,  241,  241,  241
    } ;

static const short int yy_nxt[436] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   29,   28,
       28,   30,    4,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   28,   40,   28,   41,   28,   28,   28,   28,
       42,   43,   44,   45,   46,   47,   28,   28,   28,   48,
       49,   50,   51,   54,   56,   57,   58,   63,  127,   68,
       65,   69,   69,   70,   84,   85,  115,   64,   66,   67,
       87,   59,  240,   88,   71,   72,  145,   77,   77,   79,
      100,   55,   72,  101,   73,   73,   74,  146,  239,   75,

       75,   54,   80,   74,   81,   82,   75,   75,   76,   95,
       74,   97,   92,   98,  103,  116,   75,   74,   96,   93,
      117,  104,   99,   75,   75,   94,  107,  108,  241,   55,
      156,   75,  157,   60,   76,  154,  109,   69,   69,  110,
       54,  121,  121,  155,  150,   61,  119,  120,  238,  120,
      122,  123,  125,  123,  125,  237,  148,  126,  126,  151,
      119,  120,   75,   75,  122,  123,  120,  236,   55,   72,
      123,   73,   73,  149,   72,  235,   77,   77,  234,   75,
       74,  126,  126,  124,  124,   74,  233,   75,   75,   75,
      159,  232,  159,  231,   74,  160,  160,  121,  121,   74,

      124,  230,  124,  124,  229,   75,  161,  162,  124,  162,
      163,  228,  163,   75,  227,  164,  164,  171,  172,  124,
      161,  162,  126,  126,  166,  166,  162,  124,  160,  160,
      160,  160,  165,  195,  165,  195,  164,  164,  196,  196,
      120,  166,  120,  164,  164,  226,  165,  196,  196,  166,
      225,  165,  224,  123,  120,  123,  166,  166,  223,  120,
      222,  221,  220,  219,  196,  196,  218,  123,  217,  216,
      215,  214,  123,  166,  162,  213,  162,  212,  211,  210,
      209,  166,  208,  207,  206,  205,  204,  203,  162,  202,
      201,  200,  199,  162,   53,   53,   53,   53,   60,  198,

       60,   60,   86,   86,  197,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,
      179,  178,  177,  176,  175,  174,  173,  170,  169,  168,
      167,  158,  153,  152,  147,  144,  143,  142,  141,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
       61,  129,  128,  118,  241,  114,  113,  112,  111,  106,
      105,  102,   91,   90,   89,   83,   78,   62,   61,   52,
      241,    3,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241
    } ;

static const short int yy_chk[436] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    8,    9,    9,   10,   15,  245,   18,
       17,   18,   18,   19,   26,   26,   49,   15,   17,   17,
       29,   10,  236,   29,   19,   21,  106,   21,   21,   24,
       38,    8,   20,   38,   20,   20,   21,  106,  235,   21,

       21,   53,   24,   20,   24,   24,   20,   20,   20,   36,
       21,   37,   35,   37,   40,   49,   21,   20,   36,   35,
       60,   40,   37,   20,   21,   35,   43,   43,   61,   53,
      113,   20,  113,   61,   20,  112,   43,   69,   69,   43,
       87,   72,   72,  112,  109,   60,   69,   69,  233,   69,
       72,   72,   74,   72,   74,  231,  108,   74,   74,  109,
       69,   69,   75,   75,   72,   72,   69,  230,   87,   73,
       72,   73,   73,  108,   77,  229,   77,   77,  228,   75,
       73,  125,  125,   73,   73,   77,  221,   75,   77,   77,
      119,  218,  119,  217,   73,  119,  119,  121,  121,   77,

       73,  215,  124,  124,  214,   77,  121,  121,   73,  121,
      122,  212,  122,   77,  211,  122,  122,  134,  134,  124,
      121,  121,  126,  126,  127,  127,  121,  124,  159,  159,
      160,  160,  126,  161,  126,  161,  163,  163,  161,  161,
      160,  127,  160,  164,  164,  210,  126,  195,  195,  127,
      209,  126,  208,  164,  160,  164,  166,  166,  207,  160,
      205,  204,  202,  201,  196,  196,  200,  164,  199,  194,
      193,  191,  164,  166,  196,  190,  196,  189,  188,  187,
      186,  166,  185,  184,  183,  182,  181,  178,  196,  177,
      174,  173,  172,  196,  242,  242,  242,  242,  243,  171,

      243,  243,  244,  244,  168,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      142,  140,  139,  138,  137,  136,  135,  133,  132,  131,
      130,  114,  111,  110,  107,  105,  104,  102,  101,  100,
       99,   98,   97,   96,   95,   94,   93,   92,   91,   90,
       88,   85,   81,   68,   55,   47,   46,   45,   44,   42,
       41,   39,   34,   33,   32,   25,   22,   14,   11,    7,
        3,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,

      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  241,  241
    } ;

static yy_state_type yy_last_accepting_state;
static YY_CHAR *yy_last_accepting_cpos;

#if YY_lex_DEBUG != 0
static const short int yy_rule_linenum[91] =
    {   0,
       29,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   52,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   64,   66,   67,   68,   69,   71,   72,
       73,   75,   77,   78,   79,   80,   81,   82,   83,   84,
       85,   86,   87,   88,   89,   90,   91,   92,   93,   94,
       95,   96,   97,   98,   99,  100,  101,  102,  103,  104,
      105,  106,  107,  108,  109,  110,  111,  112,  113,  114,
      115,  116,  117,  118,  119,  120,  121,  122,  124,  125
    } ;

#endif
/* the intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#line 376 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"
#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
#else
#define yy_get_previous_state() ((yy_state_type)(yy_get_previous_state_()))
#define yy_try_NUL_trans(c) ((yy_state_type)(yy_try_NUL_trans_(c)))
#endif

#ifndef YY_USE_CLASS
#ifdef YY_lex_LEX_DEFINED
YY_lex_LEX_RETURN YY_lex_LEX ( YY_lex_LEX_PARAM )
YY_lex_LEX_PARAM_DEF
#else
YY_DECL
#endif
#else
YY_lex_LEX_RETURN YY_lex_CLASS::YY_lex_LEX ( YY_lex_LEX_PARAM)

#endif
    {
    register yy_state_type yy_current_state;
    register YY_lex_CHAR *yy_cp, *yy_bp;
    register int yy_act;

/* % user's declarations go here */ 

/* % end of prolog */ 
#line 401 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"

    if ( yy_init )
	{
	 
	 {
	 YY_USER_INIT;
	 }
	if ( ! yy_start )
	    yy_start = 1;       /* first start state */

	if ( ! yy___in )
	    yy___in = YY_lex_IFILE_DEFAULT;

	if ( ! yy___out )
	    yy___out = YY_lex_OFILE_DEFAULT;

	if ( YY_lex_CURRENT_BUFFER )
	    YY_lex_INIT_BUFFER( YY_lex_CURRENT_BUFFER, yy___in );
	else
	    YY_lex_CURRENT_BUFFER = YY_lex_CREATE_BUFFER( yy___in, YY_BUF_SIZE );

	YY_lex_LOAD_BUFFER_STATE();
	yy_init=0;
	}

    while ( 1 )         /* loops until end-of-file is reached */
	{
/* % yymore()-related code goes here */ 
#line 429 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"
	yy_cp = yy_c_buf_p;

	/* support of yy___text */
	*yy_cp = yy_hold_char;

	/* yy_bp points to the position in yy_ch_buf of the start of the
	 * current run.
	 */
	yy_bp = yy_cp;

/* % code to set up and find next match goes here */ 
	yy_current_state = yy_start;
yy_match:
	do
	    {
	    register YY_CHAR yy_c = yy_ec[*yy_cp];
	    if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = yy_def[yy_current_state];
		if ( yy_current_state >= 242 )
		    yy_c = yy_meta[yy_c];
		}
	    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	    ++yy_cp;
	    }
	while ( yy_current_state != 241 );
	yy_cp = yy_last_accepting_cpos;
	yy_current_state = yy_last_accepting_state;
#line 440 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"

yy_find_action:
/* % code to find the action number goes here */ 
	yy_act = yy_accept[yy_current_state];
#line 443 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"

	YY_DO_BEFORE_ACTION;
	YY_USER_ACTION;

do_action:      /* this label is used only to access EOF actions */
#if YY_lex_DEBUG != 0
	if ( yy___flex_debug )
		{
		if ( yy_act == 0 )
#ifndef YY_lex_IOSTREAM
			fprintf( yy___stderr , "--scanner backtracking\n" );
#else
			yy___stderr <<"--scanner backtracking"<<endl;
#endif
		else if ( yy_act < YY_END_OF_BUFFER -1 )
#ifndef YY_lex_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting rule at line %d (\"%s\")\n",
			 yy_rule_linenum[yy_act], yy___text );
#else
			yy___stderr <<"--accepting rule at line "
                          <<(int)yy_rule_linenum[yy_act]
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER -1 )
#ifndef YY_lex_IOSTREAM
			fprintf( yy___stderr , 
			 "--accepting default rule (\"%s\")\n",
			 yy___text );
#else
			yy___stderr <<"--accepting default rule"
                          <<" (\""<<(char *)yy___text<<"\")"<<endl;
#endif
		else if ( yy_act == YY_END_OF_BUFFER )
#ifndef YY_lex_IOSTREAM
			fprintf( yy___stderr , "--(end of buffer or a NUL)\n" );
#else
			yy___stderr <<"--(end of buffer or a NUL)"<<endl;
#endif
		else
#ifndef YY_lex_IOSTREAM
			fprintf( yy___stderr , "--EOF\n" );
#else
			yy___stderr <<"--EOF"<<endl;
#endif
		}
#endif
	switch ( yy_act )
	    {
/* % actions go here */ 
	    case 0: /* must backtrack */
	    /* undo the effects of YY_DO_BEFORE_ACTION */
	    *yy_cp = yy_hold_char;
	    yy_cp = yy_last_accepting_cpos;
	    yy_current_state = yy_last_accepting_state;
	    goto yy_find_action;

case 1:
#line 29 "kcscanner.l"
{ comment(); }
	YY_BREAK
case 2:
#line 31 "kcscanner.l"
{ count(yytext); return(parse::AUTO); }
	YY_BREAK
case 3:
#line 32 "kcscanner.l"
{ count(yytext); return(parse::BREAK); }
	YY_BREAK
case 4:
#line 33 "kcscanner.l"
{ count(yytext); return(parse::CASE); }
	YY_BREAK
case 5:
#line 34 "kcscanner.l"
{ count(yytext); return(parse::CHAR); }
	YY_BREAK
case 6:
#line 35 "kcscanner.l"
{ count(yytext); return(parse::CONST); }
	YY_BREAK
case 7:
#line 36 "kcscanner.l"
{ count(yytext); return(parse::CONTINUE); }
	YY_BREAK
case 8:
#line 37 "kcscanner.l"
{ count(yytext); return(parse::DEFAULT); }
	YY_BREAK
case 9:
#line 38 "kcscanner.l"
{ count(yytext); return(parse::DO); }
	YY_BREAK
case 10:
#line 39 "kcscanner.l"
{ count(yytext); return(parse::DOUBLE); }
	YY_BREAK
case 11:
#line 40 "kcscanner.l"
{ count(yytext); return(parse::ELSE); }
	YY_BREAK
case 12:
#line 41 "kcscanner.l"
{ count(yytext); return(parse::ENUM); }
	YY_BREAK
case 13:
#line 42 "kcscanner.l"
{ count(yytext); return(parse::EXTERN); }
	YY_BREAK
case 14:
#line 43 "kcscanner.l"
{ count(yytext); return(parse::FLOAT); }
	YY_BREAK
case 15:
#line 44 "kcscanner.l"
{ count(yytext); return(parse::FOR); }
	YY_BREAK
case 16:
#line 45 "kcscanner.l"
{ count(yytext); return(parse::GOTO); }
	YY_BREAK
case 17:
#line 46 "kcscanner.l"
{ count(yytext); return(parse::IF); }
	YY_BREAK
case 18:
#line 47 "kcscanner.l"
{ count(yytext); return(parse::INT); }
	YY_BREAK
case 19:
#line 48 "kcscanner.l"
{ count(yytext); return(parse::LONG); }
	YY_BREAK
case 20:
#line 49 "kcscanner.l"
{ count(yytext); return(parse::REGISTER); }
	YY_BREAK
case 21:
#line 50 "kcscanner.l"
{ count(yytext); return(parse::RETURN); }
	YY_BREAK
case 22:
#line 51 "kcscanner.l"
{ count(yytext); return(parse::SHORT); }
	YY_BREAK
case 23:
#line 52 "kcscanner.l"
{ count(yytext); return(parse::SIGNED); }
	YY_BREAK
case 24:
#line 53 "kcscanner.l"
{ count(yytext); return(parse::SIZEOF); }
	YY_BREAK
case 25:
#line 54 "kcscanner.l"
{ count(yytext); return(parse::STATIC); }
	YY_BREAK
case 26:
#line 55 "kcscanner.l"
{ count(yytext); return(parse::STRUCT); }
	YY_BREAK
case 27:
#line 56 "kcscanner.l"
{ count(yytext); return(parse::SWITCH); }
	YY_BREAK
case 28:
#line 57 "kcscanner.l"
{ count(yytext); return(parse::TYPEDEF); }
	YY_BREAK
case 29:
#line 58 "kcscanner.l"
{ count(yytext); return(parse::UNION); }
	YY_BREAK
case 30:
#line 59 "kcscanner.l"
{ count(yytext); return(parse::UNSIGNED); }
	YY_BREAK
case 31:
#line 60 "kcscanner.l"
{ count(yytext); return(parse::VOID); }
	YY_BREAK
case 32:
#line 61 "kcscanner.l"
{ count(yytext); return(parse::VOLATILE); }
	YY_BREAK
case 33:
#line 62 "kcscanner.l"
{ count(yytext); return(parse::WHILE); }
	YY_BREAK
case 34:
#line 64 "kcscanner.l"
{ count(yytext); return(check_type()); }
	YY_BREAK
case 35:
#line 66 "kcscanner.l"
{ count(yytext); return(parse::CONSTANT); }
	YY_BREAK
case 36:
#line 67 "kcscanner.l"
{ count(yytext); return(parse::CONSTANT); }
	YY_BREAK
case 37:
#line 68 "kcscanner.l"
{ count(yytext); return(parse::CONSTANT); }
	YY_BREAK
case 38:
#line 69 "kcscanner.l"
{ count(yytext); return(parse::CONSTANT); }
	YY_BREAK
case 39:
#line 71 "kcscanner.l"
{ count(yytext); return(parse::CONSTANT); }
	YY_BREAK
case 40:
#line 72 "kcscanner.l"
{ count(yytext); return(parse::CONSTANT); }
	YY_BREAK
case 41:
#line 73 "kcscanner.l"
{ count(yytext); return(parse::CONSTANT); }
	YY_BREAK
case 42:
#line 75 "kcscanner.l"
{ count(yytext); return(parse::STRING_LITERAL); }
	YY_BREAK
case 43:
#line 77 "kcscanner.l"
{ count(yytext); return(parse::ELLIPSIS); }
	YY_BREAK
case 44:
#line 78 "kcscanner.l"
{ count(yytext); return(parse::RIGHT_ASSIGN); }
	YY_BREAK
case 45:
#line 79 "kcscanner.l"
{ count(yytext); return(parse::LEFT_ASSIGN); }
	YY_BREAK
case 46:
#line 80 "kcscanner.l"
{ count(yytext); return(parse::ADD_ASSIGN); }
	YY_BREAK
case 47:
#line 81 "kcscanner.l"
{ count(yytext); return(parse::SUB_ASSIGN); }
	YY_BREAK
case 48:
#line 82 "kcscanner.l"
{ count(yytext); return(parse::MUL_ASSIGN); }
	YY_BREAK
case 49:
#line 83 "kcscanner.l"
{ count(yytext); return(parse::DIV_ASSIGN); }
	YY_BREAK
case 50:
#line 84 "kcscanner.l"
{ count(yytext); return(parse::MOD_ASSIGN); }
	YY_BREAK
case 51:
#line 85 "kcscanner.l"
{ count(yytext); return(parse::AND_ASSIGN); }
	YY_BREAK
case 52:
#line 86 "kcscanner.l"
{ count(yytext); return(parse::XOR_ASSIGN); }
	YY_BREAK
case 53:
#line 87 "kcscanner.l"
{ count(yytext); return(parse::OR_ASSIGN); }
	YY_BREAK
case 54:
#line 88 "kcscanner.l"
{ count(yytext); return(parse::RIGHT_OP); }
	YY_BREAK
case 55:
#line 89 "kcscanner.l"
{ count(yytext); return(parse::LEFT_OP); }
	YY_BREAK
case 56:
#line 90 "kcscanner.l"
{ count(yytext); return(parse::INC_OP); }
	YY_BREAK
case 57:
#line 91 "kcscanner.l"
{ count(yytext); return(parse::DEC_OP); }
	YY_BREAK
case 58:
#line 92 "kcscanner.l"
{ count(yytext); return(parse::PTR_OP); }
	YY_BREAK
case 59:
#line 93 "kcscanner.l"
{ count(yytext); return(parse::AND_OP); }
	YY_BREAK
case 60:
#line 94 "kcscanner.l"
{ count(yytext); return(parse::OR_OP); }
	YY_BREAK
case 61:
#line 95 "kcscanner.l"
{ count(yytext); return(parse::LE_OP); }
	YY_BREAK
case 62:
#line 96 "kcscanner.l"
{ count(yytext); return(parse::GE_OP); }
	YY_BREAK
case 63:
#line 97 "kcscanner.l"
{ count(yytext); return(parse::EQ_OP); }
	YY_BREAK
case 64:
#line 98 "kcscanner.l"
{ count(yytext); return(parse::NE_OP); }
	YY_BREAK
case 65:
#line 99 "kcscanner.l"
{ count(yytext); return(';'); }
	YY_BREAK
case 66:
#line 100 "kcscanner.l"
{ count(yytext); return('{'); }
	YY_BREAK
case 67:
#line 101 "kcscanner.l"
{ count(yytext); return('}'); }
	YY_BREAK
case 68:
#line 102 "kcscanner.l"
{ count(yytext); return(','); }
	YY_BREAK
case 69:
#line 103 "kcscanner.l"
{ count(yytext); return(':'); }
	YY_BREAK
case 70:
#line 104 "kcscanner.l"
{ count(yytext); return('='); }
	YY_BREAK
case 71:
#line 105 "kcscanner.l"
{ count(yytext); return('('); }
	YY_BREAK
case 72:
#line 106 "kcscanner.l"
{ count(yytext); return(')'); }
	YY_BREAK
case 73:
#line 107 "kcscanner.l"
{ count(yytext); return('['); }
	YY_BREAK
case 74:
#line 108 "kcscanner.l"
{ count(yytext); return(']'); }
	YY_BREAK
case 75:
#line 109 "kcscanner.l"
{ count(yytext); return('.'); }
	YY_BREAK
case 76:
#line 110 "kcscanner.l"
{ count(yytext); return('&'); }
	YY_BREAK
case 77:
#line 111 "kcscanner.l"
{ count(yytext); return('!'); }
	YY_BREAK
case 78:
#line 112 "kcscanner.l"
{ count(yytext); return('~'); }
	YY_BREAK
case 79:
#line 113 "kcscanner.l"
{ count(yytext); return('-'); }
	YY_BREAK
case 80:
#line 114 "kcscanner.l"
{ count(yytext); return('+'); }
	YY_BREAK
case 81:
#line 115 "kcscanner.l"
{ count(yytext); return('*'); }
	YY_BREAK
case 82:
#line 116 "kcscanner.l"
{ count(yytext); return('/'); }
	YY_BREAK
case 83:
#line 117 "kcscanner.l"
{ count(yytext); return('%'); }
	YY_BREAK
case 84:
#line 118 "kcscanner.l"
{ count(yytext); return('<'); }
	YY_BREAK
case 85:
#line 119 "kcscanner.l"
{ count(yytext); return('>'); }
	YY_BREAK
case 86:
#line 120 "kcscanner.l"
{ count(yytext); return('^'); }
	YY_BREAK
case 87:
#line 121 "kcscanner.l"
{ count(yytext); return('|'); }
	YY_BREAK
case 88:
#line 122 "kcscanner.l"
{ count(yytext); return('?'); }
	YY_BREAK
case 89:
#line 124 "kcscanner.l"
{ count(yytext); }
	YY_BREAK
case 90:
#line 125 "kcscanner.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 91:
#line 127 "kcscanner.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
    yyterminate();
#line 493 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"

	    case YY_END_OF_BUFFER:
		{
		/* amount of text matched not including the EOB char */
		int yy_amount_of_matched_text = yy_cp - yy___text - 1;

		/* undo the effects of YY_DO_BEFORE_ACTION */
		*yy_cp = yy_hold_char;

		/* note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the end-
		 * of-buffer state).  Contrast this with the test in yyinput().
		 */
		if ( yy_c_buf_p <= &YY_lex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
		    /* this was really a NUL */
		    {
		    yy_state_type yy_next_state;

		    yy_c_buf_p = yy___text + yy_amount_of_matched_text;

		    yy_current_state = yy_get_previous_state();

		    /* okay, we're now positioned to make the
		     * NUL transition.  We couldn't have
		     * yy_get_previous_state() go ahead and do it
		     * for us because it doesn't know how to deal
		     * with the possibility of jamming (and we
		     * don't want to build jamming into it because
		     * then it will run more slowly)
		     */

		    yy_next_state = yy_try_NUL_trans( yy_current_state );

		    yy_bp = yy___text + YY_MORE_ADJ;

		    if ( yy_next_state )
			{
			/* consume the NUL */
			yy_cp = ++yy_c_buf_p;
			yy_current_state = yy_next_state;
			goto yy_match;
			}

		    else
			{
/* % code to do backtracking for compressed tables and set up yy_cp goes here */ 
			    yy_cp = yy_last_accepting_cpos;
			    yy_current_state = yy_last_accepting_state;
#line 541 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"
			goto yy_find_action;
			}
		    }

		else switch ( yy_get_next_buffer() )
		    {
		    case EOB_ACT_END_OF_FILE:
			{
			yy_did_buffer_switch_on_eof = 0;

			if ( yywrap() )
			    {
			    /* note: because we've taken care in
			     * yy_get_next_buffer() to have set up yy___text,
			     * we can now set up yy_c_buf_p so that if some
			     * total hoser (like flex itself) wants
			     * to call the scanner after we return the
			     * YY_NULL, it'll still work - another YY_NULL
			     * will get returned.
			     */
			    yy_c_buf_p = yy___text + YY_MORE_ADJ;

			    yy_act = YY_STATE_EOF((yy_start - 1) / 2);
			    goto do_action;
			    }

			else
			    {
			    if ( ! yy_did_buffer_switch_on_eof )
				YY_NEW_FILE;
			    }
			}
			break;

		    case EOB_ACT_CONTINUE_SCAN:
			yy_c_buf_p = yy___text + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_match;

		    case EOB_ACT_LAST_MATCH:
			yy_c_buf_p =
			    &YY_lex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars];

			yy_current_state = yy_get_previous_state();

			yy_cp = yy_c_buf_p;
			yy_bp = yy___text + YY_MORE_ADJ;
			goto yy_find_action;
		    }
		break;
		}

	    default:
#if YY_lex_DEBUG != 0
#ifndef YY_lex_IOSTREAM
		fprintf(yy___stderr , "action # %d\n", yy_act );
#else
		yy___stderr <<"action # "<<(int)yy_act<<endl;
#endif
#endif
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	    }
	}
	yyterminate();/* avoid the no return value error message on MS-C7/dos */
    }


/* yy_get_next_buffer - try to read in a new buffer
 *
 * synopsis
 *     int yy_get_next_buffer();
 *     
 * returns a code representing an action
 *     EOB_ACT_LAST_MATCH - 
 *     EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *     EOB_ACT_END_OF_FILE - end of file
 */
#ifndef YY_USE_CLASS
static int yy_get_next_buffer()
#else
int YY_lex_CLASS::yy_get_next_buffer()
#endif
    {
    register YY_lex_CHAR *dest = YY_lex_CURRENT_BUFFER->yy_ch_buf;
    register YY_lex_CHAR *source = yy___text - 1; /* copy prev. char, too */
    register int number_to_move, i;
    int ret_val;

    if ( yy_c_buf_p > &YY_lex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] )
	YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

    /* try to read more data */

    /* first move last chars to start of buffer */
    number_to_move = yy_c_buf_p - yy___text;

    for ( i = 0; i < number_to_move; ++i )
	*(dest++) = *(source++);

    if ( YY_lex_CURRENT_BUFFER->yy_eof_status != EOF_NOT_SEEN )
	/* don't do the read, it's not guaranteed to return an EOF,
	 * just force an EOF
	 */
	yy_n_chars = 0;

    else
	{
	int num_to_read = YY_lex_CURRENT_BUFFER->yy_buf_size - number_to_move - 1;

	if ( num_to_read > YY_READ_BUF_SIZE )
	    num_to_read = YY_READ_BUF_SIZE;

	else if ( num_to_read <= 0 )
	    YY_FATAL_ERROR( "fatal error - scanner input buffer overflow" );

	/* read in more data */
	YY_INPUT( (&YY_lex_CURRENT_BUFFER->yy_ch_buf[number_to_move]),
		  yy_n_chars, num_to_read );
	}

    if ( yy_n_chars == 0 )
	{
	if ( number_to_move - YY_MORE_ADJ == 1 )
	    {
	    ret_val = EOB_ACT_END_OF_FILE;
	    YY_lex_CURRENT_BUFFER->yy_eof_status = EOF_DONE;
	    }

	else
	    {
	    ret_val = EOB_ACT_LAST_MATCH;
	    YY_lex_CURRENT_BUFFER->yy_eof_status = EOF_PENDING;
	    }
	}

    else
	ret_val = EOB_ACT_CONTINUE_SCAN;

    yy_n_chars += number_to_move;
    YY_lex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_lex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    /* yy___text begins at the second character in yy_ch_buf; the first
     * character is the one which preceded it before reading in the latest
     * buffer; it needs to be kept around in case it's a newline, so
     * yy_get_previous_state() will have with '^' rules active
     */

    yy___text = &YY_lex_CURRENT_BUFFER->yy_ch_buf[1];

    return ( ret_val );
    }


/* yy_get_previous_state - get the state just before the EOB char was reached
 *
 * synopsis
 *     yy_state_type yy_get_previous_state();
 */

#ifndef YY_USE_CLASS
static yy_state_type yy_get_previous_state()
#else
long YY_lex_CLASS::yy_get_previous_state_()
#endif
    {
    register yy_state_type yy_current_state;
    register YY_lex_CHAR *yy_cp;

/* % code to get the start state into yy_current_state goes here */ 
    yy_current_state = yy_start;
#line 717 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"

    for ( yy_cp = yy___text + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
	{
/* % code to find the next state goes here */ 
	register YY_CHAR yy_c = (*yy_cp ? yy_ec[*yy_cp] : 1);
	if ( yy_accept[yy_current_state] )
	    {
	    yy_last_accepting_state = yy_current_state;
	    yy_last_accepting_cpos = yy_cp;
	    }
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	    {
	    yy_current_state = yy_def[yy_current_state];
	    if ( yy_current_state >= 242 )
		yy_c = yy_meta[yy_c];
	    }
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
#line 721 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"
	}

#ifndef YY_USE_CLASS
    return ( yy_current_state );
#else
    return (long)( yy_current_state );
#endif
    }


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *     next_state = yy_try_NUL_trans( current_state );
 */

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( register yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
register yy_state_type yy_current_state;
#endif
#else
long YY_lex_CLASS::yy_try_NUL_trans_(long yy_current_state_)
#endif

    {
#ifndef YY_USE_CLASS
#else
    yy_state_type yy_current_state=(yy_state_type)yy_current_state_;
#endif
    register int yy_is_jam;
/* % code to find the next state, and perhaps do backtracking, goes here */ 
    register YY_CHAR *yy_cp = yy_c_buf_p;

    register YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
	{
	yy_last_accepting_state = yy_current_state;
	yy_last_accepting_cpos = yy_cp;
	}
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
	{
	yy_current_state = yy_def[yy_current_state];
	if ( yy_current_state >= 242 )
	    yy_c = yy_meta[yy_c];
	}
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 241);
#line 755 "C:\\Users\\Filami\\Documents\\code\\vidf_dx12\\tools\\flexskel.cc"

#ifndef YY_USE_CLASS
    return ( yy_is_jam ? 0 : yy_current_state );
#else
    return (long)( yy_is_jam ? 0 : yy_current_state );
#endif
    }

#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
static void yyunput( YY_lex_CHAR c, register YY_lex_CHAR *yy_bp )
#else
static void yyunput( c, yy_bp )
YY_lex_CHAR c;
register YY_lex_CHAR *yy_bp;
#endif
#else
void YY_lex_CLASS::yyunput( YY_lex_CHAR c, YY_lex_CHAR *yy_bp )
#endif

    {
    register YY_lex_CHAR *yy_cp = yy_c_buf_p;

    /* undo effects of setting up yy___text */
    *yy_cp = yy_hold_char;

    if ( yy_cp < YY_lex_CURRENT_BUFFER->yy_ch_buf + 2 )
	{ /* need to shift things up to make room */
	register int number_to_move = yy_n_chars + 2; /* +2 for EOB chars */
	register YY_lex_CHAR *dest =
	    &YY_lex_CURRENT_BUFFER->yy_ch_buf[YY_lex_CURRENT_BUFFER->yy_buf_size + 2];
	register YY_lex_CHAR *source =
	    &YY_lex_CURRENT_BUFFER->yy_ch_buf[number_to_move];

	while ( source > YY_lex_CURRENT_BUFFER->yy_ch_buf )
	    *--dest = *--source;

	yy_cp += dest - source;
	yy_bp += dest - source;
	yy_n_chars = YY_lex_CURRENT_BUFFER->yy_buf_size;

	if ( yy_cp < YY_lex_CURRENT_BUFFER->yy_ch_buf + 2 )
	    YY_FATAL_ERROR( "flex scanner push-back overflow" );
	}

    if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
	yy_cp[-2] = '\n';

    *--yy_cp = c;

    /* note: the formal parameter *must* be called "yy_bp" for this
     *       macro to now work correctly
     */
    YY_DO_BEFORE_ACTION; /* set up yy___text again */
    }

#ifndef YY_USE_CLASS
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
#else
int YY_lex_CLASS::input()
#endif
    {
    int c;
    YY_lex_CHAR *yy_cp = yy_c_buf_p;

    *yy_cp = yy_hold_char;

    if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
	{
	/* yy_c_buf_p now points to the character we want to return.
	 * If this occurs *before* the EOB characters, then it's a
	 * valid NUL; if not, then we've hit the end of the buffer.
	 */
	if ( yy_c_buf_p < &YY_lex_CURRENT_BUFFER->yy_ch_buf[yy_n_chars] )
	    /* this was really a NUL */
	    *yy_c_buf_p = '\0';

	else
	    { /* need more input */
	    yy___text = yy_c_buf_p;
	    ++yy_c_buf_p;

	    switch ( yy_get_next_buffer() )
		{
		case EOB_ACT_END_OF_FILE:
		    {
		    if ( yywrap() )
			{
			yy_c_buf_p = yy___text + YY_MORE_ADJ;
			return ( EOF );
			}

		    YY_NEW_FILE;
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    return ( yyinput() );
#else
		    return ( input() );
#endif
#else
		    return ( input() );
#endif
		    }
		    break;

		case EOB_ACT_CONTINUE_SCAN:
		    yy_c_buf_p = yy___text + YY_MORE_ADJ;
		    break;

		case EOB_ACT_LAST_MATCH:
#ifndef YY_USE_CLASS
#ifdef __cplusplus
		    YY_FATAL_ERROR( "unexpected last match in yyinput()" );
#else
		    YY_FATAL_ERROR( "unexpected last match in input()" );
#endif
#else
		    YY_FATAL_ERROR( "unexpected last match in YY_lex_CLASS::input()" );
#endif
		}
	    }
	}

    c = *yy_c_buf_p;
    yy_hold_char = *++yy_c_buf_p;

    return ( c );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_lex_RESTART( YY_lex_IFILE  *input_file )
#else
void YY_lex_RESTART( input_file )
YY_lex_IFILE  *input_file;
#endif
#else
void YY_lex_CLASS::YY_lex_RESTART ( YY_lex_IFILE  *input_file )
#endif

    {
    YY_lex_INIT_BUFFER( YY_lex_CURRENT_BUFFER, input_file );
    YY_lex_LOAD_BUFFER_STATE();
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_lex_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#else
void YY_lex_SWITCH_TO_BUFFER( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
#else
void YY_lex_CLASS::YY_lex_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer )
#endif

    {
    if ( YY_lex_CURRENT_BUFFER == new_buffer )
	return;

    if ( YY_lex_CURRENT_BUFFER )
	{
	/* flush out information for old buffer */
	*yy_c_buf_p = yy_hold_char;
	YY_lex_CURRENT_BUFFER->yy_buf_pos = yy_c_buf_p;
	YY_lex_CURRENT_BUFFER->yy_n_chars = yy_n_chars;
	}

    YY_lex_CURRENT_BUFFER = new_buffer;
    YY_lex_LOAD_BUFFER_STATE();

    /* we don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yy_did_buffer_switch_on_eof = 1;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_lex_LOAD_BUFFER_STATE( void )
#else
void YY_lex_LOAD_BUFFER_STATE()
#endif
#else
void YY_lex_CLASS::YY_lex_LOAD_BUFFER_STATE(  )
#endif

    {
    yy_n_chars = YY_lex_CURRENT_BUFFER->yy_n_chars;
    yy___text = yy_c_buf_p = YY_lex_CURRENT_BUFFER->yy_buf_pos;
    yy___in = YY_lex_CURRENT_BUFFER->yy_input_file;
    yy_hold_char = *yy_c_buf_p;
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE YY_lex_CREATE_BUFFER( YY_lex_IFILE  *file, int size )
#else
YY_BUFFER_STATE YY_lex_CREATE_BUFFER( file, size )
YY_lex_IFILE  *file;
int size;
#endif
#else
YY_BUFFER_STATE YY_lex_CLASS::YY_lex_CREATE_BUFFER( YY_lex_IFILE  *file, int size )
#endif

    {
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE) malloc( sizeof( struct yy_buffer_state ) );

    if ( ! b )
	YY_FATAL_ERROR( "out of dynamic memory in YY_lex_CREATE_BUFFER()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (YY_lex_CHAR *) malloc( (unsigned) (b->yy_buf_size + 2) );

    if ( ! b->yy_ch_buf )
	YY_FATAL_ERROR( "out of dynamic memory in YY_lex_CREATE_BUFFER()" );

    YY_lex_INIT_BUFFER( b, file );

    return ( b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_lex_DELETE_BUFFER( YY_BUFFER_STATE b )
#else
void YY_lex_DELETE_BUFFER( b )
YY_BUFFER_STATE b;
#endif
#else
void YY_lex_CLASS::YY_lex_DELETE_BUFFER( YY_BUFFER_STATE b )
#endif

    {
    if ( b == YY_lex_CURRENT_BUFFER )
	YY_lex_CURRENT_BUFFER = (YY_BUFFER_STATE) 0;

    free( (char *) b->yy_ch_buf );
    free( (char *) b );
    }


#ifndef YY_USE_CLASS
#ifdef YY_USE_PROTOS
void YY_lex_INIT_BUFFER( YY_BUFFER_STATE b, YY_lex_IFILE  *file )
#else
void YY_lex_INIT_BUFFER( b, file )
YY_BUFFER_STATE b;
YY_lex_IFILE  *file;
#endif
#else
void YY_lex_CLASS::YY_lex_INIT_BUFFER( YY_BUFFER_STATE b, YY_lex_IFILE  *file)
#endif

    {
    b->yy_input_file = file;

    /* we put in the '\n' and start reading from [1] so that an
     * initial match-at-newline will be true.
     */

    b->yy_ch_buf[0] = '\n';
    b->yy_n_chars = 1;

    /* we always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[1];

    b->yy_eof_status = EOF_NOT_SEEN;
    }
#line 127 "kcscanner.l"


int yywrap()
{
	return 1;
}


void comment()
{
/*
	char c, c1;

loop:
	while ((c = input()) != '*' && c != 0)
		putchar(c);

	if ((c1 = input()) != '/' && c != 0)
	{
		unput(c1);
		goto loop;
	}

	if (c != 0)
		putchar(c1);
	*/
}


int column = 0;


void count(const char* yytext)
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n')
			column = 0;
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;
}


int check_type()
{
	return(parse::IDENTIFIER);
}
